### ISSUE TITLE
Creating a Cloud Foundry alias command is incorrect

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM-Bluemix-Docs/databases-for-redis#2]
the command is wrong on this page. As it stands, it's for viewing an existing alias, not creating a new one. It should be:

ibmcloud resource service-alias-create alias-name -g resource-group-name --instance-name instance-name
e.g.
ibmcloud resource service-alias-create example-redis -g exampleRG --instance-name exmple-redis

**Comment by DailyAlice** [comment]
Not sure if this was part of another ticket and might have gotten fixed in the past, but the docs currently use the format of the [`ibmcloud resource service-alias-create`](https://cloud.ibm.com/docs/cli?topic=cloud-cli-ibmcloud_commands_resource#ibmcloud_resource_service_alias_create) command. Closing.
